<a href="https://colab.research.google.com/github/Azamat2023/BlogProject/blob/master/9_32_Pandas_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)

#Data Sayns va Sunʼiy Intellekt Praktikum

#9.32. Pandas kutubxonasi boʻyicha amaliy vazifa.

Yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtiririlgan`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va uni chop eting.

In [8]:
import pandas as pd
import numpy as np

**2.** Versiya va konfiguratsiyani tekshiring.

In [9]:
print(pd.__version__)

1.5.3


**3.** Pandas kutubxonasida mavjud boʻlgan barcha versiya maʼlumotlarini chop eting.

In [10]:
print(pd.show_versions())


INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.26100
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.3
numpy            : 1.25.0
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 67.8.0
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brot

## `📌DataFrame: Asoslar`

DataFramesʼda maʼlumotlarni tanlash (selecting), saralash (sorting), qoʻshish (adding) va yigʻish (aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang.
``` python
import numpy as np
```

Quyidagi Python lugʻati (dictionary) `data` va Python roʻyxati (list) `labels` ni koʻrib chiqing.


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```



In [12]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [14]:
print(data)
print(labels)

{'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'], 'age': [2.5, 3, 0.5, nan, 5, 2, 4.5, nan, 7, 3], 'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


**4.** Ushbu `lugʻat` (dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [15]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
df
# (Dasturni davom ettiring!)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Ushbu DataFrame va uning maʼlumotlari haqidagi asosiy maʼlumotlarning qisqacha mazmunini koʻrsating.

`💡Ishora:` DataFrameʼda chaqirilishi mumkin boʻlgan yagona usul mavjud.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [17]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`ʼdan faqat `animal` va `age` ustunlarini tanlang.

In [18]:
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi maʼlumotlarni tanlang.

In [33]:
df.iloc[[3, 4, 8], [0, 1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan koʻp boʻlgan qatorlarni tanlang.

In [35]:
df[df.visits>=3]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

10. Yosh yoʻqolgan qatorlarni tanlang, yaʼni `NaN`.

In [41]:
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik boʻlgan umumiy qatorlarni tanlang.

In [43]:
df[(df.animal=='cat') & (df.age<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [45]:
df[(df.age >= 2) & (df.age <= 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** `f` qatoridagi yoshni `1,5` ga oʻzgartiring.

In [50]:
df.at['f', 'age'] = 1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yigʻindisini hisoblang.

In [51]:
df.visits.sum()

19

**15.** Har bir `animal` uchun oʻrtacha yoshni `df` da hisoblang.

In [60]:
l = ['cat', 'dog', 'snake']
for i in l:
    print(f"{i}ning o'rtcha yoshi {df[df.animal == i]['age'].mean()}")

catning o'rtcha yoshi 2.3333333333333335
dogning o'rtcha yoshi 5.0
snakening o'rtcha yoshi 2.5


**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [74]:
df.animal.value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

**17.** `animal` ustunida, `snake` soʻzini `python` soʻziga oʻzgartiring.

In [94]:
df.loc[['c', 'g'], ['animal']] = 'python'
df

animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  2.0       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

## `📌DataFrame: Murakkab`

### Darajasi murakkabroq vazifa: toʻgʻri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak boʻlishi mumkin

Oldingi boʻlim DataFrameʼning asosiy, ammo muhim operatsiyalari boʻyicha vazifalari jamlagan edi. Quyida maʼlumotlarni kesishingiz kerak boʻlgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni oʻz ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni oʻz ichiga olgan ustun paydo boʻlishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [95]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df

A
0   1
1   2
2   2
3   3
4   4
5   5
6   5
7   5
8   6
9   7
10  7

**19.** Raqamli qiymatlardan iborat DataFrame berildi.

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 oʻlchovi
```

Qatordagi har bir elementdan satrning oʻrtacha qiymatini qanday ayirish mumkin?

In [103]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
mean = df.mean()
df - mean

0         1         2
0 -0.026556  0.140155  0.088843
1 -0.029165 -0.237450 -0.201585
2 -0.036325  0.383300  0.092069
3  0.372036 -0.070211  0.286504
4 -0.279990 -0.215794 -0.265831

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yigʻindisi eng kichik ekanini hisoblang. U ustunning yorligʻini qaytaring.

In [108]:
df = pd.DataFrame(np.random.random(size=(5, 10)))
df.sum(axis=1).idxmin()

4

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrameʼning har bir qatori uchun uchinchi `NaN` qiymatini oʻz ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [155]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# bu usulni chatgpt dan o'rgandim to'g'risi o'zim bajara olmadim
third_nan_cols = df.apply(lambda row: row[row.isnull()].index[2], axis=1)

print(third_nan_cols.tolist())

# Javobni bu yerga yozing.



['e', 'c', 'd', 'h', 'd']


**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [220]:
# Javobni bu yerga yozing.
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

result = df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum()).sort_index()

print(result)

grps
a    409
b    156
c    345
Name: vals, dtype: int64


**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega `A` va `B`. `A` dagi qiymatlar 1 dan 100 gacha (shu jumladan).

`A` dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yigʻindisini hisoblang.

Javob quyidagicha boʻlishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [222]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# A ustunini intervalga bo‘lish
bins = pd.cut(df['A'], bins=np.arange(0, 101, 10))  # (0,10], (10,20], ..., (90,100]

# Har bir guruh bo‘yicha B ustunini yig‘ish
result = df.groupby(bins)['B'].sum()

print(result)

# Javobni bu yerga yozing!

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int32


**24.** 'X' butun son ustuni boʻlgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha boʻlishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [225]:
#javobni bu yerga yozing!
import pandas as pd

df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

# 0 ko‘rinishidagi indexlarni topamiz
zero_indices = df.index[df['X'] == 0].tolist()
zero_indices = [-1] + zero_indices  # boshidan boshlash uchun

# Y ustunini yaratamiz
Y = []
for i in range(len(df)):
    # oxirgi 0 indexini topamiz
    last_zero_index = max([z for z in zero_indices if z <= i])
    Y.append(i - last_zero_index)

df['Y'] = Y
print(df['Y'].tolist())

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]


##`📌Maʼlumotlarni tozalash`

Bu har doim sodir boʻladi: kimdir sizga notoʻgʻri tuzilgan satrlar, roʻyxatlar va yetishmayotgan maʼlumotlarni oʻz ichiga olgan maʼlumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan soʻng u quyidagi koʻrinishga ega boʻlishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


In [226]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**26.** **FlightNumber** ustunidagi baʼzi qiymatlar yoʻq. Ular `NaN` koʻrinishida yozilgan. Bu raqamlar har bir qatorda 10 ga koʻpayishi kerak, shuning uchun 10055 va 10075 ni qoʻyish kerak. Ushbu yetishmayotgan raqamlarni toʻldirish uchun `df` ni oʻzgartiring va ustunni butun son ustuniga aylantiring.

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df.at[1, "FlightNumber"] = 10055
df.at[3, "FlightNumber"] = 10075
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN       10055.0            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis       10075.0          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**27.** **From\_To** ustunini ikkita alohida ustun koʻrinishida yozing.                                          

Toʻgʻri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [2]:
df[['From', 'To']] = df['From_To'].str.split('_', expand=True)
df.drop("From_To", axis=1)

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    LoNDon      paris
1       10055.0            []    <Air France> (12)    MAdrid      miLAN
2       10065.0  [24, 43, 87]  (British Airways. )    londON  StockhOlm
3       10075.0          [13]       12. Air France  Budapest      PaRis
4       10085.0      [67, 32]          "Swiss Air"  Brussels     londOn

**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.
Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" boʻlishi kerak.)

In [8]:
df.From = df.From.str.title()
df

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      paris
1       10055.0            []    <Air France> (12)    Madrid      miLAN
2       10065.0  [24, 43, 87]  (British Airways. )    London  StockhOlm
3       10075.0          [13]       12. Air France  Budapest      PaRis
4       10085.0      [67, 32]          "Swiss Air"  Brussels     londOn

**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va boshqa belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ''(British Airways. )'' `British Airways` koʻrinishida yozilishi kerak.

In [10]:
import re
# Tozalash funksiyasi
def clean_airline(name):
    # Belgilarni olib tashlaymiz, faqat harf va bo‘sh joy qoladi
    return re.sub(r'[^a-zA-Z ]', '', name).strip()

# Qo‘llash
df['Airline'] = df['Airline'].apply(clean_airline)
df

FlightNumber  RecentDelays          Airline      From         To
0       10045.0      [23, 47]              KLM    London      paris
1       10055.0            []       Air France    Madrid      miLAN
2       10065.0  [24, 43, 87]  British Airways    London  StockhOlm
3       10075.0          [13]       Air France  Budapest      PaRis
4       10085.0      [67, 32]        Swiss Air  Brussels     londOn

**30.** `df` dan **From_To** ustunini oʻchiring va Temporary DataFrame `temp` ustunini qoʻshing.

In [12]:
df['temp'] = 0
df

FlightNumber  RecentDelays          Airline      From         To  temp
0       10045.0      [23, 47]              KLM    London      paris     0
1       10055.0            []       Air France    Madrid      miLAN     0
2       10065.0  [24, 43, 87]  British Airways    London  StockhOlm     0
3       10075.0          [13]       Air France  Budapest      PaRis     0
4       10085.0      [67, 32]        Swiss Air  Brussels     londOn     0

**31**. `RecentDelays` ustunida qiymatlar DataFrameʼga roʻyxat sifatida kiritilgan. Vazifangiz birinchi, har bir ikkinchi qiymatni oʻz ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat boʻlmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi koʻrinishda boʻlishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [13]:
# RecentDelays ustunini yangi ustunlarga kengaytirish
delays = pd.DataFrame(df['RecentDelays'].tolist(), columns=['delay_1', 'delay_2', 'delay_3'])

# Asl DataFramega qo‘shamiz
df = df.drop('RecentDelays', axis=1)
df = pd.concat([df, delays], axis=1)
df

FlightNumber          Airline      From         To  temp  delay_1  delay_2  \
0       10045.0              KLM    London      paris     0     23.0     47.0   
1       10055.0       Air France    Madrid      miLAN     0      NaN      NaN   
2       10065.0  British Airways    London  StockhOlm     0     24.0     43.0   
3       10075.0       Air France  Budapest      PaRis     0     13.0      NaN   
4       10085.0        Swiss Air  Brussels     londOn     0     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

##`📌Minesweeper`


### Minesweeper tarmogʻida xavfsiz kvadratlar uchun raqamlar yaratamiz.

💡 Agar siz Windowsʼning avvalgi versiyalaridan foydalangan boʻlsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz oʻyin bilan tanish boʻlmasangiz, kvadratchalar toʻplamini tasavvur qiling: bu kvadratlarning baʼzilari mineʼni yashiradi. Agar siz mineʼni bossangiz, darhol yoʻqotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qoʻshni boʻlgan kvadratchalarda qancha mine borligini koʻrsatadigan raqamni koʻrasiz. Oʻyinning maqsadi toʻrdagi mine boʻlmagan barcha kvadratlarni ochishdir.

Ushbu boʻlimda Minesweeper oʻyini uchun kerakli maʼlumotlarni oʻz ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qoʻshni kvadratlarda topilgan mineʼlar sonini aniqlaymiz.

**32**. Tasavvur qiling, biz Minesweeper oʻyinini 5 dan 4 gacha boʻlgan panjarada oʻynayapmiz, yaʼni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani oʻz ichiga olgan `'x'` va `'y'`. Yaʼni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [15]:
# O'lchamlar
x = 5
y = 4

df = pd.DataFrame([(i, j) for i in range(x) for j in range(y)], columns=['x', 'y'])
df

x  y
0   0  0
1   0  1
2   0  2
3   0  3
4   1  0
5   1  1
6   1  2
7   1  3
8   2  0
9   2  1
10  2  2
11  2  3
12  3  0
13  3  1
14  3  2
15  3  3
16  4  0
17  4  1
18  4  2
19  4  3

**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir boʻlish ehtimoli 0,4 boʻlishi kerak.

In [17]:
# Avvalgi df dan foydalanamiz (100 ta satr)
df = pd.DataFrame(
    np.random.RandomState(8765).randint(1, 101, size=(100, 2)),
    columns=["A", "B"]
)

# 0.4 ehtimollik bilan mina joylash (1 - mina, 0 - xavfsiz)
np.random.seed(42)  # Reproduktivlik uchun
df['mine'] = np.random.choice([0, 1], size=len(df), p=[0.6, 0.4])

# 'safe' ustuni - minalarning teskarisi
df['safe'] = 1 - df['mine']
df

A   B  mine  safe
0   46  29     0     1
1   75  22     1     0
2   49  63     1     0
3   33  43     0     1
4   71  75     0     1
..  ..  ..   ...   ...
95  60  87     0     1
96  57  40     0     1
97  86  19     0     1
98  50  56     0     1
99  97  94     0     1

[100 rows x 4 columns]

 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qoʻshni kvadratlarda topilgan mineʼlar soni boʻlishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv boʻlgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [ ]:
import numpy as np
import pandas as pd
from scipy.ndimage import convolve

# 1. Tasodifiy sonlar bilan DataFrame yaratish
df = pd.DataFrame(
    np.random.RandomState(8765).randint(1, 101, size=(100, 2)),
    columns=["A", "B"]
)

# 2. 40% ehtimollik bilan 'mine' ustuni yaratish
np.random.seed(42)
df['mine'] = np.random.choice([0, 1], size=100, p=[0.6, 0.4])

# 3. 'mine' ustunini 10x10 gridga aylantirish
mine_grid = df['mine'].values.reshape((10, 10))

# 4. Qo‘shni kataklardagi minalarni hisoblash uchun kernel
kernel = np.array([[1, 1, 1],
                   [1, 0, 1],
                   [1, 1, 1]])

# 5. Konvolyutsiya yordamida 'adjacent' qiymatlarni hisoblash
adjacent_grid = convolve(mine_grid, kernel, mode='constant', cval=0)

# 6. 'adjacent' ustunini asl DataFrame'ga qo‘shish
df['adjacent'] = adjacent_grid.reshape(100)

# 7. Natijani tekshirish
print(df.head(10))

**35**. Mineʼni oʻz ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga oʻzgartiring.

In [ ]:
df.loc[df['mine'] == 1, 'adjacent'] = np.nan

**36**. DataFrame-ni `adjacent` mineʼlar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [ ]:
# 10x10 panjara ko'rinishida qayta shakllantiramiz
adjacent_grid = df['adjacent'].values.reshape((10, 10))

# Panjarani DataFrame ko'rinishida yasaymiz
adjacent_df = pd.DataFrame(adjacent_grid)

# Ustunlar va qatorlarni aniq ifodalash
adjacent_df.columns.name = 'x'
adjacent_df.index.name = 'y'

##📌BONUS vazifa

Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.